# Site Settings
title: Kevin Glück
email: kevin.glueck@gmx.de
description: > # Hier kannst du einen längeren Beschreibungstext einfügen
  Kevin Glück's Homepage. 

# URL- und Host-Einstellungen
url: "https://kevglu.github.io" # Die Basis-URL (ohne abschließenden Schrägstrich)
baseurl: ""                   # Leer lassen, wenn die Seite unter der Root-Domain läuft

# Build-Einstellungen
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
markdown: kramdown            # Der Markdown-Parser
permalink: pretty             # Erzeugt saubere URLs (z.B. /ueber-uns/ statt /ueber-uns.html)

# This gives you ability to change layout of a type of page (here posts) or files in a folder
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts" # previously `post` in Jekyll 2.2.
#     values:
#       layout: "default"

# Navigation bar links
nav_links:
  - title: Home
    url: /
  # - title: About
  #   url: /about/
  - title: Blog
    url: /blog/

# Ausschlüsse (Dateien oder Ordner, die Jekyll beim Generieren ignorieren soll)
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
