# Site Settings
title: Kevin Glück
email: kevin.glueck@gmx.de
description: > # Hier kannst du einen längeren Beschreibungstext einfügen
  Kevin Glück's Homepage. 

# URL- und Host-Einstellungen
url: "https://kevglu.github.io" # Die Basis-URL (ohne abschließenden Schrägstrich)
baseurl: ""                   # Leer lassen, wenn die Seite unter der Root-Domain läuft

# Build-Einstellungen
theme: slate                 # Das verwendete Jekyll-Theme
markdown: kramdown            # Der Markdown-Parser
permalink: pretty             # Erzeugt saubere URLs (z.B. /ueber-uns/ statt /ueber-uns.html)

# Ausschlüsse (Dateien oder Ordner, die Jekyll beim Generieren ignorieren soll)
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
